# Site settings
title: 
email: 
description: > # A simple website "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman  # The Jekyll theme you want to use
markdown: kramdown  # The Markdown parser/renderer you want to use

# Build settings
markdown: kramdown
